apiVersion: v1
kind: Config
preferences: {}
current-context: dev-cluster

# Define clusters
clusters:
- name: dev-cluster
  cluster:
    server: https://dev.example.com:6443
    certificate-authority-data: SGVsbG8sIHRoaXMgaXMgYSBkdW1teSBjZXJ0aWZpY2F0ZSE=
- name: staging-cluster
  cluster:
    server: https://staging.example.com:6443
    certificate-authority-data: SGVsbG8sIHRoaXMgaXMgYSBkdW1teSBjZXJ0aWZpY2F0ZSE=
- name: production-cluster
  cluster:
    server: https://production.example.com:6443
    certificate-authority-data: SGVsbG8sIHRoaXMgaXMgYSBkdW1teSBjZXJ0aWZpY2F0ZSE=
- name: gke-project1
  cluster:
    server: https://gke-project1.example.com:6443
    certificate-authority-data: SGVsbG8sIHRoaXMgaXMgYSBkdW1teSBjZXJ0aWZpY2F0ZSE=
- name: aws-east
  cluster:
    server: https://aws-east.example.com:6443
    certificate-authority-data: SGVsbG8sIHRoaXMgaXMgYSBkdW1teSBjZXJ0aWZpY2F0ZSE=
- name: aws-west
  cluster:
    server: https://aws-west.example.com:6443
    certificate-authority-data: SGVsbG8sIHRoaXMgaXMgYSBkdW1teSBjZXJ0aWZpY2F0ZSE=

# Define users
users:
- name: dev-user
  user:
    client-certificate-data: SGVsbG8sIHRoaXMgaXMgYSBkdW1teSBjZXJ0aWZpY2F0ZSE=
    client-key-data: SGVsbG8sIHRoaXMgaXMgYSBkdW1teSBrZXkh
- name: admin-user
  user:
    client-certificate-data: SGVsbG8sIHRoaXMgaXMgYSBkdW1teSBjZXJ0aWZpY2F0ZSE=
    client-key-data: SGVsbG8sIHRoaXMgaXMgYSBkdW1teSBrZXkh
- name: prod-user
  user:
    client-certificate-data: SGVsbG8sIHRoaXMgaXMgYSBkdW1teSBjZXJ0aWZpY2F0ZSE=
    client-key-data: SGVsbG8sIHRoaXMgaXMgYSBkdW1teSBrZXkh
- name: gke-user
  user:
    auth-provider:
      config:
        access-token: ya29.dummy-token
        cmd-args: config config-helper --format=json
        cmd-path: /path/to/gcloud
        expiry: "2023-12-31T23:59:59Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
- name: aws-user
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - token
      - -i
      - eks-cluster
      command: aws-iam-authenticator
      env: null

# Define contexts
contexts:
- name: dev-cluster
  context:
    cluster: dev-cluster
    namespace: dev-frontend
    user: dev-user
- name: dev-cluster-backend
  context:
    cluster: dev-cluster
    namespace: dev-backend
    user: dev-user
- name: staging-cluster
  context:
    cluster: staging-cluster
    namespace: staging
    user: admin-user
- name: production-cluster
  context:
    cluster: production-cluster
    namespace: production
    user: prod-user
- name: gke-project1-staging
  context:
    cluster: gke-project1
    namespace: staging
    user: gke-user
- name: gke-project1-production
  context:
    cluster: gke-project1
    namespace: production
    user: gke-user
- name: aws-east-dev
  context:
    cluster: aws-east
    namespace: development
    user: aws-user
- name: aws-east-prod
  context:
    cluster: aws-east
    namespace: production
    user: aws-user
- name: aws-west-dev
  context:
    cluster: aws-west
    namespace: development
    user: aws-user
